version: '3'
services:
  flask:    
    build: ./PulsuPro_test_app
    container_name: PulsuPro_test_app   
    restart: on-failure  
    volumes:
      - ./PulsuPro_test_app:/PulsuPro_test_app
    ports:
      - "5000:5000"
    command: python app.py